export const Colors = {
  primary: '#6B041D',
  primaryDark: '#4D000F',
  gold: '#D4A017',
  goldLight: '#E8C547',
  background: '#FFFFFF',
  gradientStart: '#FFCDD9',
  gradientMid: '#FFE5EC',
  gradientEnd: '#FFFFFF',
  text: '#1A1A1A',
  textSecondary: '#6B6B6B',
  textLight: '#9E9E9E',
  label: '#2C2C2C',
  placeholder: '#B0B0B0',
  border: '#C8C8C8',
  inputBg: '#FFFFFF',
  white: '#FFFFFF',
  black: '#000000',
  error: '#D32F2F',
  socialButtonBg: '#FFFFFF',
  checkboxBorder: '#C8C8C8',
  divider: '#D4D4D4',
};
