export const Strings = {
  appName: 'PiyariFamily',
  tagline: 'Made in Heaven',
  splashTagline: 'made in heaven',

  welcomeBack: 'Welcome Back',
  loginSubtitle: 'Log in to continue your journey',
  emailLabel: 'Email Address',
  emailPlaceholder: 'you@example.com',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Enter your password',
  forgotPassword: 'Forgot Password?',
  logIn: 'Log In',
  or: 'or',
  continueGoogle: 'Continue with Google',
  continueApple: 'Continue with Apple',
  noAccount: "Don't have an account?",
  createAccount: 'Create Account',

  createYourAccount: 'Create Your Account',
  signUpSubtitle: 'Start your journey to finding love ♡',
  fullNameLabel: 'Full Name',
  fullNamePlaceholder: 'Enter your full name',
  signUpEmailPlaceholder: 'Enter your email',
  createPasswordPlaceholder: 'Create a password',
  confirmPasswordLabel: 'Confirm Password',
  confirmPasswordPlaceholder: 'Confirm your password',
  termsPrefix: 'I agree to the ',
  termsOfService: 'Terms of Service',
  termsAnd: ' and ',
  privacyPolicy: 'Privacy Policy',
  alreadyHaveAccount: 'Already have an account?',
  logInLink: 'Log In',
};
