export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    VERIFY_EMAIL_OTP: '/verify-email-otp',
    RESEND_EMAIL_OTP: '/resend-email-otp',
    FORGOT_PASSWORD: '/forgot-password',
    VERIFY_RESET_OTP: '/verify-reset-otp',
    SET_NEW_PASSWORD: '/set-new-password',
    CHANGE_PASSWORD: '/change-password',
    LOGOUT: '/logout',
  },
  PROFILE: '/profile',
  PROFILE_COUNTRY: '/profile/country',
  PROFILE_BASIC_INFO: '/profile/basic-info',
  PROFILE_EDUCATION: '/profile/education',
  PROFILE_PHYSICAL: '/profile/physical',
  PROFILE_CAREER: '/profile/career',
  PROFILE_FAITH: '/profile/faith',
  PROFILE_PHOTOS: '/profile/photos',
  PROFILE_UPDATE: '/profile/update',
  VERIFY_PHONE_SEND: '/verify-phone/send',
  VERIFY_PHONE_VERIFY: '/verify-phone/verify',
  SHORTLIST: '/shortlist',
  REFERRALS_STATS: '/referrals/stats',
  REFERRALS_HISTORY: '/referrals/history',
  MATCHES_HOME: '/matches/home',
  MATCHES_SEARCH: '/matches/search',
  MATCHES_FILTER: '/matches/filter',
  MATCHES: '/matches',
  SUBSCRIPTIONS: '/subscriptions',
} as const;
